plugin/cache: Set min TTL default to zero
coredns/coredns pull request #2199
Opened 2018-10-15 17:26 UTC by chrisohaver

### 1. Why is this pull request needed and what does it do?

IIUC, #2055 changed default behavior of caching:

Before #2055, we used the message TTL when caching, even if the message had a TTL below the `MinimalDefaultTTL`.  `MinimalDefaultTTL` was only used in cache when synthesizing TTLs for negative responses that had no SOA record.

After #2055, if any message has a TTL below the `MinimalDefaultTTL`, the cache uses the `MinimalDefaultTTL` value instead of the message TTL.

Setting the default values for `minTTL` and `minNTTL` to 0 instead of `MinimalDefaultTTL` should restore the original default behavior.

### 2. Which issues (if any) are related?

#2189

### 3. Which documentation changes (if any) need to be made?

2018-10-15 17:39 UTC, grobie commented
Sounds like we should add a test to ensure the cache plugin doesn't extends the original message TTL.

2018-10-15 17:41 UTC, fturib approved these changes
LGTM.

2018-10-15 17:45 UTC, fturib commented
@grobie : this PR is about ensuring that, BY DEFAULT, the cache will not extend the original TTL. 
But, if you change the minTTL of the cache - in purpose in the Corefile -, then the original TTL will be increased to match the minTLL of the cache.
Looks like it is expected behavior of the PR that introduced the minTTL/maxTTL for cache.
see #2055.

2018-10-15 17:46 UTC, fturib commented
hum... maybe you are right a UT that check we do not extend by default would ensure nobody will change that default behavior.

2018-10-15 17:48 UTC, fturib requested changes
Please add UT to check that TTL is not change for: replies with TTL=0, TTL=1 at least.

2018-10-15 21:28 UTC, chrisohaver commented
@fturib, test added

2018-10-15 22:18 UTC, fturib approved these changes

2018-10-16 13:00 UTC, chrisohaver commented
Would have been good to get this into 1.2.3, so we didn't have a release with the regression present.

2018-10-16 13:21 UTC, grobie approved these changes

2018-10-16 13:24 UTC, merged