Remove deprecated function calls flagged by staticcheck
coredns/coredns pull request #3333
Opened 2019-09-30 14:11 UTC by erbesharat

### 1. Why is this pull request needed and what does it do?
Removes deprecated function calls flagged by staticcheck in grpc test and route53 setup file.

### 2. Which issues (if any) are related?
fixes #3327 
fixes #3328 

### 3. Which documentation changes (if any) need to be made?
Nothing

### 4. Does this introduce a backward incompatible change or deprecation?
No

2019-09-30 15:25 UTC, miekg requested changes
lgtm, one comment

2019-09-30 15:25 UTC, miekg commented on plugin/route53/setup.go
> +			return plugin.Error("route53", c.Errf("couldn't create aws session: %s", err.Error()))
```suggestion
			return plugin.Error("route53", err)
```

2019-09-30 15:40 UTC, erbesharat commented
Sorry for the force pushes. Thought GitHub would take care of DCO when a change suggestion is applied.

2019-10-01 06:42 UTC, miekg commented
this ci failures are a red herring.

2019-10-01 06:42 UTC, merged