Bump version and amend notes to include latest PRs
coredns/coredns pull request #4634
Opened 2021-05-18 11:49 UTC by miekg

Signed-off-by: Miek Gieben <miek@miek.nl>

2021-05-18 11:55 UTC, SuperQ approved these changes
LGTM, nice.

2021-05-18 11:55 UTC, SuperQ commented on notes/coredns-1.8.4.md
> +
Extra newline?

2021-05-18 12:46 UTC, chrisohaver requested changes
LGTM + some small fixes, and also etcd is releasing 3.5 this week, they just dropped 3.5.0beta. Probably should at least bump to latest beta ...

2021-05-18 12:46 UTC, chrisohaver commented on notes/coredns-1.8.4.md
>  * plugin/dnssec: heck for two days of remaining validity (https://github.com/coredns/coredns/pull/4606)
```suggestion
* plugin/dnssec: Check for two days of remaining validity (https://github.com/coredns/coredns/pull/4606)
```

2021-05-18 12:46 UTC, chrisohaver commented on notes/coredns-1.8.4.md
> +* plugin/etcd: Fix etcd to use v3.5.0-alpha.0 (https://github.com/coredns/coredns/pull/4628)
v3.5.0-beta.1 just got released.

2021-05-18 12:46 UTC, chrisohaver commented on notes/coredns-1.8.4.md
> +It also include a fix when using the "reverse zone syntax", i.e. 10.0.0.0/15, now return the proper
```suggestion
It also include a fix when using the "reverse zone cidr syntax", e.g. 10.0.0.0/15, now return the proper
```

2021-05-18 14:09 UTC, chrisohaver commented
> ... etcd is releasing 3.5 this week ...

Clarification - they _started the release process this week_, code freeze yesterday. Reading the 3.5.0 beta CHANGELOG, looks like the final release is slated for June, which is a ways off.

2021-05-20 13:52 UTC, chrisohaver commented on notes/coredns-1.8.4.md
> +* plugin/etcd: Fix etcd to use v3.5.0-alpha.0 (https://github.com/coredns/coredns/pull/4628)
```suggestion
* plugin/etcd: Bump etcd to v3.5.0-beta.3 (https://github.com/coredns/coredns/pull/4638)
```

2021-05-24 20:18 UTC, chrisohaver commented
Given that #4621 will require updates in almost external plugins, should we bump the minor version?  I.e. to v1.9.0 instead of v1.8.4.

2021-05-25 14:13 UTC, chrisohaver commented on notes/coredns-1.8.4.md
> +It also include a fix when using the "reverse zone syntax", i.e. 10.0.0.0/15, now return the proper
Should highlight required changes to existing external plugins introduce with the plugin level reverse zone changes.

2021-05-25 14:27 UTC, chrisohaver requested changes

2021-05-25 14:27 UTC, chrisohaver commented on notes/coredns-1.8.4.md
>  * plugin/bind: Bind by interface name (https://github.com/coredns/coredns/pull/4522)
```suggestion
* reverse zone: make Normalize return proper reverse zones (https://github.com/coredns/coredns/pull/4621)
* plugin/bind: Bind by interface name (https://github.com/coredns/coredns/pull/4522)
```

2021-05-25 14:27 UTC, chrisohaver commented on notes/coredns-1.8.4.md
```suggestion
**NOTE:** This release is backward incompatible with external plugins that uses `Host.Normalize()`. See https://github.com/coredns/coredns/pull/4621 for examples of how to update plugins.
```

2021-05-28 10:14 UTC, merged