plugin/kubernetes: consistently choose EndpointSlices or Endpoints for unstable API
coredns/coredns pull request #4647
Opened 2021-05-25 02:52 UTC by uesyn

Signed-off-by: uesyn <suemura@zlab.co.jp>

### 1. Why is this pull request needed and what does it do?

In the current implementation, CoreDNS gives up the use of EndpointSlices and falls back to Endpoints when Kubernetes API is temporarily unavailable. This behavior may cause inconsistent query results if there are multiple CoreDNS instances, and some use EndpointSlices, others use Endpoints.
EndpointSlices are not mirrored to Endpoints, so CoreDNS may fail to resolve a name for a service that has only EndpointSlice as backend if this problem occurs.
This PR makes CoreDNS consistently choose EndpointSlices or Endpoints.

### 2. Which issues (if any) are related?

### 3. Which documentation changes (if any) need to be made?

### 4. Does this introduce a backward incompatible change or deprecation?

2021-05-25 13:18 UTC, chrisohaver requested changes
Thank you! I didn't think this would be an issue because the server version is checked first, and I had assumed that if the Kubernetes API could answer that, then the API was "available."  But I presume you have _observed_ this is not the case? Or is this to protect against the API becoming unavailable in between checking the version and checking for Endpointslice support?

Looks like the key change here is checking for errors other than the "not found" error.

I've suggested some changes to logged warnings - some of which would be logged too frequently while the API is not available.

2021-05-25 13:18 UTC, chrisohaver commented on plugin/kubernetes/kubernetes.go
> +				log.Warningf("Failed to get kubernetes version: %s", err)
Please remove this warning, I think this would be too verbose.  It would get logged 10 times per second until the API is up.

2021-05-25 13:18 UTC, chrisohaver commented on plugin/kubernetes/kubernetes.go
> +				log.Warningf("Failed to discovery %s: %s", discovery.SchemeGroupVersion.String(), err)
This is also too verbose, if this state can persist for more than a millisecond. I think it can be removed

2021-05-25 13:18 UTC, chrisohaver commented on plugin/kubernetes/kubernetes.go
> +				log.Warningf("Failed to discovery %s: %s", discoveryV1beta1.SchemeGroupVersion.String(), err)
Same as above, re: verbosity.

2021-05-25 13:18 UTC, chrisohaver commented on plugin/kubernetes/kubernetes.go
> +			log.Info("Watching Endpoints instead of EndpointSlices")
```suggestion
			log.Info("Endpointslices API disabled. Watching Endpoints instead. ")
```

2021-05-27 12:29 UTC, uesyn commented
@chrisohaver 
Thank you for your review! I applied all your suggestions!

> Thank you! I didn't think this would be an issue because the server version is checked first, and I had assumed that if the Kubernetes API could answer that, then the API was "available." But I presume you have observed this is not the case? Or is this to protect against the API becoming unavailable in between checking the version and checking for Endpointslice support?

I haven't observed at CoreDNS yet, but I think this could happen.
I tested the below code in the situation that kube-apiserver returns too many requests and got an error as expected.
This situation may be a rare case, but it is worth taking into account because the choice of either EndpointSlices or Endpoints affects until terminating a CoreDNS.

```go
func main() {
	clientset, err := NewClientSet()
	if err != nil {
		log.Fatalf("Failed to get clientset: %s", err)
	}

	for {
		var err error

		_, err = clientset.ServerVersion()
		if err != nil {
			continue
		}

		if _, err = clientset.Discovery().ServerResourcesForGroupVersion(discovery.SchemeGroupVersion.String()); err == nil {
			// Here is unreachable. In k8s v1.19, always got error, because K8s v1.19 doesn't support discovery v1.
			continue
		}

		if _, err = clientset.Discovery().ServerResourcesForGroupVersion(discoveryv1beta1.SchemeGroupVersion.String()); err == nil {
			continue
		}

		log.Printf("Got error: %s", err)
	}
}
```

2021-05-27 12:38 UTC, chrisohaver approved these changes
Thanks! I think this is safe and could protect against cases where the connection to the API is unstable.

2021-05-27 12:48 UTC, merged