plugin:Reset dns question name if NS loopkup fail
coredns/coredns pull request #4824
Opened 2021-08-25 13:43 UTC by changqingsun

### **1. Why is this pull request needed and what does it do?**
When I used both etcd plugin and forward plugin, It cannot resolve the NS record of the root domain name.

cmd `dig -t NS .`
resolve time out.

At this time, I found two phenomena：

- coredns logs print "NS: dns: bad rdata".
- it still in loop until defaultTimeout，causing high cpu usage

The reason of this question is that the question section of packet which forwarded by forward plugin is` ns.dns..`  Instead of` . `. 
So the forward plugin print bad rdata Error.

Question section is setted in backend_lookup.go,  I think if NS lookup fail ,  it should reset this question section.

so I commit this PR.

### **2. Which issues (if any) are related?**
forward causing high cpu usage #4544
I use the etcd plug-in to forward all the analysis, and I encountered a CPU usage of 300% #4649 

### **3. Which documentation changes (if any) need to be made?**
No.

### **4. Does this introduce a backward incompatible change or deprecation?**
No.

I verified in our test environment that this commit  is  work.

2021-08-25 13:55 UTC, chrisohaver commented
Hmm.. I think this change makes sense. But also ~IMO `dnsutil.Join` should be creating valid output... i.e. it should be fixed to  handle joining a root domain correctly.~

Actually - I think we're passing the "label" to `Join` incorrectly... https://github.com/coredns/coredns/pull/4824#discussion_r695784481

2021-08-25 14:02 UTC, chrisohaver commented on plugin/backend_lookup.go
>  	state.Req.Question[0].Name = dnsutil.Join("ns.dns.", zone)
```suggestion
	state.Req.Question[0].Name = dnsutil.Join("ns.dns", zone)
```

2021-08-26 06:13 UTC, changqingsun commented on plugin/backend_lookup.go
>  	state.Req.Question[0].Name = dnsutil.Join("ns.dns.", zone)
I try this commit in my test env.  But i still can not work with command `"dig +t NS ."`

the cmd return:
```
dig -t NS . @localhost
;; Question section mismatch: got ns.dns/NS/IN
;; Question section mismatch: got ns.dns/NS/IN
;; Question section mismatch: got ns.dns/NS/IN
;; Question section mismatch: got ns.dns/NS/IN
```
Catch the packet 

```
request ： 	DNS	77	Standard query 0x83a0 NS ns.dns OPT
reply  	DNS	1063	Standard query response 0x83a0 No such name NS ns.dns SOA a.root-servers.net NSEC do NSEC aaa RRSIG RRSIG RRSIG OPT
```
So use question name ns.dns  can not get result from upstream server. 

But in my opinion, this commit is needed.  and  need modify function `dnsutil.Join`

```
func Join(labels ...string) string {
	ll := len(labels)
	if labels[ll-1] == "." {
		//return strings.Join(labels[:ll-1], ".") + "."
                return "."
	}
	return dns.Fqdn(strings.Join(labels, "."))
}
```

2021-08-26 12:11 UTC, chrisohaver commented on plugin/backend_lookup.go
> +	m.RecursionAvailable = true
None of the backend plugins currently implement recursion - so setting this flag is not correct.

2021-08-26 12:11 UTC, chrisohaver commented on plugin/etcd/handler.go
> +	m.RecursionAvailable = true
The etcd plugin does not implement recursion.

2021-08-26 12:29 UTC, changqingsun commented on plugin/backend_lookup.go
>  	state.Req.Question[0].Name = dnsutil.Join("ns.dns.", zone)
@chrisohaver  disscuss this issue ? 
i try  use this ? it does still not work.
```
func Join(labels ...string) string {
	ll := len(labels)
	if labels[ll-1] == "." {
		//return strings.Join(labels[:ll-1], ".") + "."
                return "."
	}
	return dns.Fqdn(strings.Join(labels, "."))
}
```

2021-08-26 12:34 UTC, chrisohaver commented on plugin/backend_lookup.go
>  	state.Req.Question[0].Name = dnsutil.Join("ns.dns.", zone)
> @chrisohaver disscuss this issue ?
> i try use this ? it does still not work.
> 
> ```
> func Join(labels ...string) string {
> 	ll := len(labels)
> 	if labels[ll-1] == "." {
> 		//return strings.Join(labels[:ll-1], ".") + "."
>                 return "."
> 	}
> 	return dns.Fqdn(strings.Join(labels, "."))
> }
> ```

This will ignore all other labels when last label is a ".", which is definitely not what we want to happen. Note that `dnsutil.Join` is a utility function used in many places - not just here.

2021-08-26 13:11 UTC, changqingsun commented on plugin/backend_lookup.go
>  	state.Req.Question[0].Name = dnsutil.Join("ns.dns.", zone)
the  commit which you suggestion  doesn't not work still ....  it can not relose my issue 
`state.Req.Question[0].Name = dnsutil.Join("ns.dns", zone)`

2021-08-26 13:19 UTC, chrisohaver commented
> the commit which you suggestion doesn't not work still ... `;; Question section mismatch: got ns.dns/NS/IN`

I suspect you tried it without your fix to restore the question - that's also needed.

2021-08-26 13:24 UTC, chrisohaver commented on plugin/backend_lookup.go
> +		state.Req.Question[0].Name = old
``` go
	services, err := b.Services(ctx, state, false, opt)
 	if err != nil {
 		state.Req.Question[0].Name = old
 		return nil, nil, err
 	}
 	// ... and reset
	state.Req.Question[0].Name = old
```

shorter ... 

``` go
	services, err := b.Services(ctx, state, false, opt)
 	// ... and reset
	state.Req.Question[0].Name = old
 	if err != nil {
 		return nil, nil, err
 	}
```

2021-08-26 13:49 UTC, changqingsun commented on plugin/backend_lookup.go
> +		state.Req.Question[0].Name = old
OK, I agree with you this change. 
```
	services, err := b.Services(ctx, state, false, opt)
 	// ... and reset
	state.Req.Question[0].Name = old
 	if err != nil {
 		return nil, nil, err
 	}

```
this fix can reslove my issue. 

I modify this commit as the shorter, and remove  ra flag commit.

2021-08-27 11:44 UTC, miekg commented
the root domain is not supported in the etcd plugin and breaks stuff IIRC

2021-08-27 11:57 UTC, chrisohaver commented
If we merge, before merging, we need to be make sure we don't break K8s NS queries, which use the same backend function.
I don't recall if there is an end to end test for it.

2021-08-27 12:12 UTC, changqingsun commented
> If we merge, before merging, we need to be make sure we don't break K8s NS queries, which use the same backend function.
> I don't recall if there is an end to end test for it.

OK ,  I update this commit,  please help me to check it.   I can pass my test in my env.   but I didn't test  K8S NS queries.

I'll try my best  find K8S environment and test that.   Or is there any feasible test method on your side?

2021-08-27 12:45 UTC, chrisohaver commented
I’ll look into adding an end to end test for it.

2021-08-29 13:08 UTC, changqingsun commented
> I’ll look into adding an end to end test for it.

OK ,  Thanks a lot.

2021-08-30 20:58 UTC, chrisohaver commented
Added an NS query test to **ci/circleci: kubernetes-tests**

2021-08-30 21:15 UTC, chrisohaver approved these changes

2021-08-31 05:08 UTC, changqingsun commented
> Added an NS query test to **ci/circleci: kubernetes-tests**
> 
> re-ran it in this PR ... and it passed.

OK,  Thank you very much for your help.

2021-08-31 07:48 UTC, miekg commented
This needs an intree test as well. Would like that to see fail unless this patch is applied

2021-08-31 09:06 UTC, changqingsun commented
> This needs an intree test as well. Would like that to see fail unless this patch is applied

What is intree test ？ How to do it.     I tested in my test env , it can not reslove root domain use etcd plugin and forward plugin  without this patch.

2021-08-31 11:35 UTC, chrisohaver commented
> > This needs an intree test as well. Would like that to see fail unless this patch is applied
> 
> What is intree test ？ How to do it. I tested in my test env , it can not reslove root domain use etcd plugin and forward plugin without this patch.

Add a unit test to this PR that tests the code in a way that it would fail if this fix is was not in place.

2021-09-07 13:40 UTC, chrisohaver requested changes
Thanks.  Please add a unit test.

2021-09-13 06:37 UTC, changqingsun commented
> Thanks. Please add a unit test.

OK ， I will do it as soon as possible

2021-09-28 16:52 UTC, changqingsun commented
> Thanks. Please add a unit test.

I write a testcase in  plugin/etcd/lookup_test.go

but i run it ... show me  no tests to run .
```
MacBook etcd % ls 
README.md      cname_test.go  etcd.go        group_test.go  handler.go     log_test.go    lookup_test.go msg            multi_test.go  other_test.go  setup.go       setup_test.go  xfr.go
MacBook etcd % go test .
ok      github.com/coredns/coredns/plugin/etcd  (cached) [no tests to run]

```

Is my execution method wrong?

2021-09-28 17:03 UTC, chrisohaver commented
@changqingsun, that file has a build tag `// +build etcd`... so it doesn't get built unless you build with that tag.
It has a build tag because the test requires a local etcd server to be configured and running.

It would probably be better to test the `NS` function directly in a new file `backend_lookup_test.go`, passing a `ServiceBackend` test stub.

2021-09-30 11:44 UTC, changqingsun commented
> @changqingsun, that file has a build tag `// +build etcd`... so it doesn't get built unless you build with that tag. It has a build tag because the test requires a local etcd server to be configured and running.
> 
> It would probably be better to test the `NS` function directly in a new file `backend_lookup_test.go`, passing a `ServiceBackend` test stub.

hi, chrisohaver,   This issue only happened when use etcd and forward scenes.  only test NS,  i still use etcd servicebackend...   I don‘t konw  how to do it . can you help me ? 


input   NS .
expect result :  err   (real is err...)

2021-09-30 12:07 UTC, chrisohaver commented
> > @changqingsun, that file has a build tag `// +build etcd`... so it doesn't get built unless you build with that tag. It has a build tag because the test requires a local etcd server to be configured and running.
> > It would probably be better to test the `NS` function directly in a new file `backend_lookup_test.go`, passing a `ServiceBackend` test stub.
> 
> hi, chrisohaver, This issue only happened when use etcd and forward scenes. only test NS, i still use etcd servicebackend... I don‘t konw how to do it . can you help me ?
> 
> input NS . expect result : err (real is err...)

For the test, define an new object that minimally implements servicebackend. Then pass that object to the function.

2022-01-07 15:42 UTC, chrisohaver commented
@changqingsun, do you plan to complete this PR?

2022-01-26 15:08 UTC, closed without merging