Fix broken URL link in 1.8.0 release note
coredns/coredns pull request #4875
Opened 2021-09-21 05:42 UTC by vanou

### 1. Why is this pull request needed and what does it do?

This PR fixes broken URL link to plugins/dnstap in release note.

### 2. Which issues (if any) are related?
NONE

### 3. Which documentation changes (if any) need to be made?
NONE

### 4. Does this introduce a backward incompatible change or deprecation?
NONE

2021-09-21 13:43 UTC, chrisohaver requested changes
Thanks, I think an absolute link would work better than a relative one.  Please also sign the DCO.

2021-09-23 04:41 UTC, vanou commented
> Thanks, I think an absolute link would work better than a relative one. Please also sign the DCO.

Thanks @chrisohaver . I added DCO.
I think link notation like this ``/plugins/dnstap`` is better than absolute link because
- If CoreDNS change structure of their site, it's easy to modify URLs in their documentation because of consistency with another document (another documents use relative link ,e.g. ``/plugins/dnstap``)

2021-09-23 13:10 UTC, chrisohaver commented
> another documents use relative link ,e.g. /plugins/dnstap

Ah right, the links are intended to work in the context of coredns.io, not here (github.com).

2021-09-30 02:59 UTC, vanou commented
Thanks @chrisohaver . Can we go forward?

2021-09-30 03:12 UTC, chrisohaver commented
> Thanks @chrisohaver . Can we move forward?

Please sign the DCO

2021-09-30 03:18 UTC, chrisohaver commented
Ah I see it’s signed, but just the name on email doesn’t match.

2021-09-30 03:20 UTC, merged