file plugin: add minInterval avoid cpu load too high
coredns/coredns pull request #4944
Opened 2021-11-01 04:33 UTC by sstoner

Signed-off-by: vanceli <vanceli@tencent.com>

### 1. Why is this pull request needed and what does it do?
when plugin `file` reload duration is too low:
the CPU: 
![image](https://user-images.githubusercontent.com/17512778/139621768-d63f86d8-802c-4e8c-ab27-47b70d55290c.png)

![wecom-temp-65bfbd4e2a0ed182c01534f267feb5cd](https://user-images.githubusercontent.com/17512778/139621662-71ac6748-65e9-4d80-a023-8b8e83ff2e7f.png)

### 2. Which issues (if any) are related?
none

### 3. Which documentation changes (if any) need to be made?
we should notify users when they set these args

https://github.com/coredns/coredns/blob/master/plugin/file/README.md#syntax

### 4. Does this introduce a backward incompatible change or deprecation?
No

2021-11-01 15:03 UTC, chrisohaver requested changes
Thanks!

I'm not sure if 2 seconds is too high, or even if we should impose a minimum at all. Nevertheless if we do, the README should document it.

Technically this change alters the syntax since it would allow a bare `reload` without a duration. I don't think that change is necessary.  Although, it would be much better to error out than to crash when DURATION is not specified (as the existing code in master does now).

2021-11-02 03:07 UTC, sstoner commented
> I'm not sure if 2 seconds is too high, or even if we should impose a minimum at all. Nevertheless if we do, the README should document it.

I will do the benchmark and post the result here 

> Technically this change alters the syntax since it would allow a bare reload without a duration.

the document said `Default is one minute`, but the default value is never used unless we set a specific value for `reload`. The crash may not be friendly...

2021-11-03 02:52 UTC, sstoner commented
I test again... CPU load will rise obviously when the duration is set below the millisecond level. If it's not necessary, I will close this MR

900 µs
![image](https://user-images.githubusercontent.com/17512778/140003702-ee75e859-2d1e-4914-94db-84e217d4b24f.png)

1ms 
![image](https://user-images.githubusercontent.com/17512778/140003911-236c0b56-8ba9-4d6d-9bc0-bbee811aa38f.png)

2021-11-04 14:57 UTC, chrisohaver commented
> the document said Default is one minute, but the default value is never used unless we set a specific value for reload.

IIRC, the default is used if `reload` is not specified at all.

I'm hesitant to merge this as is since it introduces a backward incompatibility for anyone with a reload set to less than 2 seconds.

2021-11-06 06:57 UTC, closed without merging