plugin/file: Fix print tree error
coredns/coredns pull request #4962
Opened 2021-11-05 15:35 UTC by victory460

Signed-off-by: xuweiwei <xuweiwei_yewu@cmss.chinamobile.com>

### 1. Why is this pull request needed and what does it do?
the print by level of tree can not work correctly, if the tree has 4 nodes, it shoud print three line node , but it will print all node contain in the two line. For more detail,you can see _print_test.go_.
### 2. Which issues (if any) are related?
No.
### 3. Which documentation changes (if any) need to be made?
No.
### 4. Does this introduce a backward incompatible change or deprecation?
No.

2021-11-05 15:44 UTC, chrisohaver commented
@victory460, you can push new commits to an existing PR without closing and re-opening a new PR for each change.

re: #4945 #4947 #4948 #4955 #4959

2021-11-05 15:50 UTC, victory460 commented
> @victory460, you can push new commits to an existing PR without closing and re-opening a new PR for each change.
> 
> re: #4945 #4947 #4948 #4955 #4959

OK. Thank you for your guidance.

2021-11-09 14:46 UTC, chrisohaver requested changes
The test provided doesn't have any fail conditions - so unless it crashes, it will always pass.

The unit test should fail if tested against the current code in master, and pass when tested against the fixed code in the PR.

2021-11-10 09:55 UTC, victory460 commented
> The test provided doesn't have any fail conditions - so unless it crashes, it will always pass.
> 
> The unit test should fail if tested against the current code in master, and pass when tested against the fixed code in the PR.

Thank you for your review:smile: . According to your suggestions, I updated the unit test code.

2021-11-12 16:25 UTC, miekg commented
1 more request. Can you put in the git commit what printed wrong now and how that looks with this fix?

2021-11-15 02:41 UTC, victory460 commented
> 1 more request. Can you put in the git commit what printed wrong now and how that looks with this fix?

Thank you for your review gratefully. I updated the git commit content and the description of this PR.

2021-11-15 05:06 UTC, yongtang commented
@victory460 I noticed that your commit's email is not associated with your GitHub ID. I would suggest you to update the email of the commit, or add the email to GitHub's associated email address as otherwise your work will not be attributed to you.

2021-11-15 05:21 UTC, victory460 commented
> @victory460 I noticed that your commit's email is not associated with your GitHub ID. I would suggest you to update the email of the commit, or add the email to GitHub's associated email address as otherwise your work will not be attributed to you.

Thanks a lot！According to your suggestion, I added my commit's email address to my github account in email setting now.

2021-11-19 02:52 UTC, Rosalieww commented
We also found the bug in this print tree code, can you merge the PR when you have time for it? Thanks.   @miekg @chrisohaver

2021-11-19 03:07 UTC, chrisohaver approved these changes

2021-11-19 16:18 UTC, miekg commented
/merge

On Fri, 19 Nov 2021, 04:07 chrisohaver, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/coredns/coredns/pull/4962#pullrequestreview-810721189>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACWIW2MUTNW56V7Q6UN5FLUMW5QDANCNFSM5HODS4ZQ>
> .
>

2021-11-19 16:18 UTC, merged