plugin/loadbalance: add cname shuffle support
coredns/coredns pull request #4971
Opened 2021-11-09 03:26 UTC by victory460

Signed-off-by: xuweiwei <xuweiwei_yewu@cmss.chinamobile.com>

### 1. Why is this pull request needed and what does it do?
https://github.com/coredns/coredns/blob/06e3b2e85994c180e1f8febebae1b11370789596/plugin/loadbalance/loadbalance.go#L34-L48

As shown in the code above, the cname record is obtained, but there is no shuffle cname in the code behind.

### 2. Which issues (if any) are related?
No.
### 3. Which documentation changes (if any) need to be made?
Loadbalance readme file has changed.
### 4. Does this introduce a backward incompatible change or deprecation?
No.

2021-11-09 13:31 UTC, chrisohaver commented
Unlike some other record types, such as A or AAAA, CNAME record names must be unique.  IOW, if you query for `test.example.com` you can only ever get one answer CNAME record back with a name of `test.example.com`.

You _can_ get multiple CNAMEs of _different_ names in a response, where the multiple CNAME records form a chain.  But, most client resolvers are sensitive to CNAME order, and will get confused if a CNAME targets a record earlier in the list.  Even if clients could handle out of order CNAME chains, randomizing the chain order would not provide a randomized answer.

So, I don't think this is necessary.

If you actually encountered a scenario where you need to randomize CNAME order, can you describe it in detail?

2021-11-09 14:39 UTC, chrisohaver reviewed
Unlike some other record types such as A or AAAA, CNAME record names must be unique.  IOW, if you query for `test.example.com` you can only ever get one CNAME record back with a name of `test.example.com`.

You _can_ get multiple CNAMEs of _different_ names in a response, where the multiple CNAME records form a chain.  But, most client resolvers are sensitive to CNAME order, and will get confused if a CNAME targets a record earlier in the list.  Even if clients could handle out of order CNAME chains, randomizing the chain order would not provide a randomized answer.

So, I don't think this is necessary.

If you actually encountered a scenario where you need to randomize CNAME order, can you describe it in detail?

2021-11-10 02:16 UTC, victory460 commented
> Unlike some other record types such as A or AAAA, CNAME record names must be unique. IOW, if you query for `test.example.com` you can only ever get one CNAME record back with a name of `test.example.com`.
> 
> You _can_ get multiple CNAMEs of _different_ names in a response, where the multiple CNAME records form a chain. But, most client resolvers are sensitive to CNAME order, and will get confused if a CNAME targets a record earlier in the list. Even if clients could handle out of order CNAME chains, randomizing the chain order would not provide a randomized answer.
> 
> So, I don't think this is necessary.
> 
> If you actually encountered a scenario where you need to randomize CNAME order, can you describe it in detail?

Thank you for your review. The scenario we considered at the beginning was to use CDN services from multiple companies for load balancing. You are right, so I modified this PR that to move case dns.TypeCNAME to the default: branch.

2021-11-10 12:00 UTC, chrisohaver requested changes
It’s unclear what bug you are aiming to fix. Can you give an example of a query with the current unexpected response, and what the expected response should be?

2021-11-10 12:00 UTC, chrisohaver commented on plugin/loadbalance/loadbalance.go
> -	out := append(cname, rest...)
Removing this will place CNAMEs after their targets, 
which will break dns resolution for some/most clients.

2021-11-10 13:01 UTC, victory460 commented on plugin/loadbalance/loadbalance.go
> -	out := append(cname, rest...)
Thanks！

2021-11-10 13:02 UTC, closed without merging