fix: convert key to domain
coredns/coredns pull request #5064
Opened 2022-01-01 18:52 UTC by soulfy

If the Key ends with '/', there'll be an extra character '.' at the beginning of the Domain.

2022-01-06 21:12 UTC, chrisohaver commented on plugin/etcd/msg/path_test.go
> +func TestPath(t *testing.T) {
A function with the same name is declared 10 lines earlier in the same file. Did you test this?

2022-01-06 21:18 UTC, chrisohaver commented on plugin/etcd/msg/path_test.go
> +	}
These errors should be more descriptive.

2022-01-06 21:23 UTC, chrisohaver commented
Not sure if a trailing `/` in a key is valid in the SkyDNS schema?  It looks to be valid in etcd, but all SkyDNS examples that I see have no trailing slash. Guessing it is valid, or at least couldn't hurt to accept.

2022-01-10 03:14 UTC, soulfy commented
> Not sure if a trailing `/` in a key is valid in the SkyDNS schema? It looks to be valid in etcd, but all SkyDNS examples that I see have no trailing slash. Guessing it is valid, or at least couldn't hurt to accept.

Sorry, previously I only executed a single test case, but didn't finish compiling.

In my scenario, there is indeed a  trailing `/` in a key, and it's valid in etcd.

2022-01-10 14:19 UTC, chrisohaver requested changes
Perhaps someone more familiar with SkyDNS and etcd can answer...
Is a trailing slash in a key is valid in the _SkyDNS_ schema? It is clearly a valid key in etcd (but that doesn't necessarily mean it's valid in SkyDNS).
Is a key without a trailing slash considered equal to the same key with a trailing slash in etcd?

2022-01-10 14:19 UTC, chrisohaver commented on plugin/etcd/msg/path_test.go
> +	}
These test failures should be more descriptive.

2022-01-14 14:24 UTC, soulfy commented
> Perhaps someone more familiar with SkyDNS and etcd can answer... Is a trailing slash in a key is valid in the _SkyDNS_ schema? It is clearly a valid key in etcd (but that doesn't necessarily mean it's valid in SkyDNS). Is a key without a trailing slash considered equal to the same key with a trailing slash in etcd?

In my test, a key without a trailing slash is actually equal to the same key with a trailing slash in etcd.

Anyway, i think this fix can increase compatibility. :-)

2022-01-14 14:31 UTC, chrisohaver commented
>> It is clearly a valid key in etcd

> In my test, a key without a trailing slash is actually equal to the same key with a trailing slash _in etcd_.

That isn't in doubt.  The question is "is a trailing slash in a key is valid in _the SkyDNS schema_?".
SkyDNS being a _subset_ of etcd. I _think_ it probably is.  But someone who knows SkyDNS better should confirm.  If there is no one that can confirm, it looks ok to me.

2022-01-14 14:40 UTC, soulfy commented
In the customised skydns I'm involved in, that was it.

2022-01-26 15:21 UTC, chrisohaver requested changes

2022-01-26 15:21 UTC, chrisohaver commented on plugin/etcd/msg/path_test.go
> +	}
This was marked resolved - but no changes were made.  The errors are non-descriptive and identical, so it's impossible to know which one failed if one does, and the other does not.   An error should _at the very least_ provide a means of uniquely identifying which test failed.  Better, would be to also show the expected result and the incorrect result. Best would be to also briefly describe what is being tested.  Please see other tests in the project as examples.

2022-01-27 03:40 UTC, soulfy commented
> Edit: Actually, since the errors are on separate lines, a failure can be traced back to the specific failed test case but one should not have to trace a test case back to test code to determine what the expected value was. Please make the error more descriptive than "==>", as suggested above.

sorry, just realized what was wrong  🤣

2022-01-27 12:49 UTC, chrisohaver approved these changes

2022-01-27 15:26 UTC, chrisohaver approved these changes
LGTM. No other reviews, so will merge.

2022-01-27 15:26 UTC, chrisohaver commented
Oh.  Please sign the commits.

2022-01-28 02:12 UTC, soulfy commented
> Oh. @soulfy, please [sign the commits](https://github.com/coredns/coredns/pull/5064/checks?check_run_id=4961249280).

😢

2022-02-01 14:45 UTC, merged