Limit release to draft only
coredns/coredns pull request #5154
Opened 2022-02-02 22:59 UTC by yongtang

A separate step is to push the button of draft to publish it.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

2022-02-02 23:25 UTC, chrisohaver requested changes
If the reason for this change is to defer the release trigger action until after the uploads are complete, it should update the release to be not a draft after the uploads are done.

2022-02-03 02:09 UTC, chrisohaver requested changes

2022-02-03 02:09 UTC, chrisohaver commented on Makefile.release
> +            -d '{"drafe":"false"}' )
```suggestion
            -d '{"draft":"false"}' )
```

2022-02-03 12:28 UTC, yongtang commented
@chrisohaver  PR updated.

2022-02-03 18:24 UTC, chrisohaver commented
https://github.com/coredns/coredns/pull/5146#issuecomment-1029264341

2022-02-03 18:24 UTC, closed without merging