Fix an array out of bounds index issue
coredns/coredns pull request #5214
Opened 2022-02-28 21:56 UTC by yongtang

This PR tries to address an array out-of-bounds index issue
that may pose security risks, by adding array length check.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### 1. Why is this pull request needed and what does it do?

### 2. Which issues (if any) are related?

### 3. Which documentation changes (if any) need to be made?

### 4. Does this introduce a backward incompatible change or deprecation?

2022-02-28 22:34 UTC, greenpau approved these changes

2022-02-28 22:35 UTC, greenpau commented
@yongtang , adding a test would help.

2022-03-01 14:32 UTC, chrisohaver commented
Please describe what plugin the fix is in in PR description/title or commit message.

2022-03-01 18:12 UTC, chrisohaver commented
> @yongtang , adding a test would help.

I don't think a test can be added, because this condition will never happen.

As a result of the logic prior to the check, args cannot be < 3 if matchType = RegexMatch.
If args < 2, we return early.
If args == 2, we set match type to exact.

2022-03-01 18:21 UTC, chrisohaver requested changes
I don't think the range check is currently necessary due to the logic above it.

2022-03-01 18:36 UTC, yongtang commented
@greenpau @chrisohaver  It looks like this is a false positive of DAST scan result from LTGM.com:
https://lgtm.com/projects/g/coredns/coredns/?mode=list

While the index bound will not be hit, I did update the PR and re-arrange the logic so that it will not hit the false positive (this is the only positive remaining). The re-arrange also avoid an extra assign (not a big diff, though).

2022-03-01 19:33 UTC, chrisohaver approved these changes
LGTM - I'm not offended by nested ifs and else statements.

2022-03-01 19:33 UTC, merged