Unit test - onstartup.go
coredns/coredns pull request #5262
Opened 2022-03-14 21:46 UTC by neilnaveen

### 1. Why is this pull request needed and what does it do?
- Included test for onstartup.go.

Signed-off-by: neil <42328488+neilnaveen@users.noreply.github.com>

### 2. Which issues (if any) are related?

### 3. Which documentation changes (if any) need to be made?

### 4. Does this introduce a backward incompatible change or deprecation?

2022-03-14 21:46 UTC, neilnaveen commented
@yongtang 👀 please

2022-03-17 14:56 UTC, neilnaveen commented
> @yongtang 👀 please

A friendly reminder!

2022-04-27 18:51 UTC, chrisohaver commented on core/dnsserver/onstartup_test.go
> +			want: "udpexample.com:dns://",
the expected values are very confusing.

2022-04-27 18:53 UTC, chrisohaver commented
@neilnaveen, Thank you for contributing. Why are you adding this?  Did you find an issue with the code?  Are you adding it just to increase reported coverage?

2022-04-27 21:04 UTC, chrisohaver requested changes
Ive suggested some changes to make expected values in the test cases to make more sense.

Should also add a test case that tests multiple zones are sorted in the in the output.

2022-04-27 21:04 UTC, chrisohaver commented on core/dnsserver/onstartup_test.go
> +				protocol: "udp",
```suggestion
				protocol: "proto://",
```

2022-04-27 21:04 UTC, chrisohaver commented on core/dnsserver/onstartup_test.go
> +			want: "udpexample.com:4005 on 127.0.0.1",
```suggestion
			want: "proto://example.com:4005 on 127.0.0.1",
```

2022-04-27 21:04 UTC, chrisohaver commented on core/dnsserver/onstartup_test.go
> +				protocol: "udp",
```suggestion
				protocol: "proto://",
```

2022-04-27 21:04 UTC, chrisohaver commented on core/dnsserver/onstartup_test.go
> +			want: "udpexample.com:dns://",
```suggestion
			want: "proto://example.com:dns://",
```

2022-06-06 02:14 UTC, closed without merging