Unit test - request/writer.go
coredns/coredns pull request #5263
Opened 2022-03-15 01:15 UTC by nathannaveen

### 1. Why is this pull request needed and what does it do?

- Implemented unit tests for request/writer.go

2022-03-15 01:15 UTC, nathannaveen commented
@yongtang 👀 please!

2022-04-27 21:35 UTC, chrisohaver requested changes
I don't think these tests are helpful.

2022-04-27 21:35 UTC, chrisohaver commented on request/writer_test.go
> +func TestNewScrubWriter(t *testing.T) {
This test is not needed.  `NewScrubWriter` is a one line function - too simple to warrant this.

2022-04-27 21:35 UTC, chrisohaver commented on request/writer_test.go
> +func TestScrubWriter_WriteMsg(t *testing.T) {
This doesn't appear to be testing anything that `WriteMsg` does.

2022-06-01 16:44 UTC, closed without merging