Included additional tests for server.go
coredns/coredns pull request #5269
Opened 2022-03-17 15:49 UTC by neilnaveen

### 1. Why is this pull request needed and what does it do?
- Included additional tests for server.go

Signed-off-by: neil <42328488+neilnaveen@users.noreply.github.com>

### 2. Which issues (if any) are related?

### 3. Which documentation changes (if any) need to be made?

### 4. Does this introduce a backward incompatible change or deprecation?

2022-03-22 20:57 UTC, neilnaveen commented
@yongtang can you please review?

2022-04-27 21:23 UTC, chrisohaver requested changes
Neither of the functions tested warrant such complex test cases.
They are both one line functions that simply return a single struct field.

Were these tests created by a unit test code generator?

2022-04-27 21:23 UTC, chrisohaver commented on core/dnsserver/server_test.go
> -
removing this line will cause import order/grouping tests to fail.

2022-04-27 21:23 UTC, chrisohaver commented on core/dnsserver/server_test.go
> +func TestServer_Address(t *testing.T) {
`Server.Address` is a single line function that returns simply Addr field.
It's too simple to warrant a test of this bulk.

2022-04-27 21:23 UTC, chrisohaver commented on core/dnsserver/server_test.go
> +			name: "nil case",
"nil case" doesn't describe this case. ":53" isn't nil.

2022-06-06 02:14 UTC, closed without merging