plugin/forward: configurable domain support for healthcheck
coredns/coredns pull request #5281
Opened 2022-03-22 03:47 UTC by hansedong

Signed-off-by: hansedong <admin@yinxiaoluo.com>

### 1. Why is this pull request needed and what does it do?

Add support for configurable domains for the health_check configuration item in the forward plugin.

In some cases, CoreDNS is deployed in a company's internal network and cannot resolve .NS records. If health check is enabled, CoreDNS will use the .NS record as the request method for health check.

At this time, if the upstream DNS Server does not have the ability to resolve .NS records, or the response to resolve .NS records is very slow (for example, the DNS Server is not in the United States), but it is very fast to resolve other domestic domain names. In this case, using .NS records as a fixed detection method will cause the health check to fail all the time.

### 2. Which issues (if any) are related?

#5121 

### 3. Which documentation changes (if any) need to be made?

https://coredns.io/plugins/forward/

### 4. Does this introduce a backward incompatible change or deprecation?

No

2022-03-22 14:10 UTC, chrisohaver requested changes
Thanks. Please also update the README.

2022-03-22 14:10 UTC, chrisohaver commented on plugin/forward/health_test.go
> +		t.Errorf("Expected number of health checks with RecursionDesired==false to be %d, got %d", 1, i1)
Please adjust the message to fit the case being tested.

2022-03-28 16:24 UTC, chrisohaver approved these changes
lgtm thanks!

2022-03-29 05:03 UTC, hansedong commented
@chrisohaver Thanks, by the way, do I need to update the content related to the forward plugin in the [github.com/coredns/coredns.io](https://github.com/coredns/coredns.io) project?

2022-03-29 11:38 UTC, chrisohaver commented
> do I need to update the content related to the forward plugin in the [github.com/coredns/coredns.io](https://github.com/coredns/coredns.io) project?


No, we have a script that copies those from this repo when we cut new releases.

2022-04-12 16:39 UTC, merged