plugin/bind: add support for bind IPv4 subnet ip
coredns/coredns pull request #5354
Opened 2022-04-28 08:10 UTC by victory460

Signed-off-by: xuweiwei <xuweiwei_yewu@cmss.chinamobile.com>

### 1. Why is this pull request needed and what does it do?
 Add support for bind IPv4 subnet ip.
```
. {
    bind 10.0.0.0/16
}
```
### 2. Which issues (if any) are related?
None.

### 3. Which documentation changes (if any) need to be made?
None.

### 4. Does this introduce a backward incompatible change or deprecation?
No.

2022-04-28 14:20 UTC, chrisohaver requested changes
Please describe in detail what this option does (or what you intend it to do).

When you open a PR, the template asks some questions.  At a minimum, please answer those when you open PRs.
* What does this PR do.
* Why is it needed.

2022-05-05 03:50 UTC, victory460 commented
Thanks for you review.

> Please describe in detail what this new feature does (or rather what you intend it to do).
> 
> When you open a PR, the template asks some questions. At a minimum, please answer those when you open PRs - especially when there is not a linked issue providing context.
> 
> * What does this PR do.

This PR add ability to bind IPv4 subnet ip.
```
. {
    bind 10.0.0.0/16
}
```

> * Why is it needed.

Scenes: 
Different clients or different regions initiate DNS requests with different destination IP in the subnet .  
Then external auxiliary configuration routing will route these dns request traffic to the coredns with the pre-configured binding subnet ip.
Then you can get different serverIp, map to get different client/region, and then transfer it to next plugin to process it.

2022-05-05 13:16 UTC, chrisohaver commented
OK, that didn't clarify it for me at all.  But I'm guessing that...

By binding to a subnet, you intend it to be shorthand for binding to every address that falls within that subnet.

For example: Let's say you have a system with three addresses 10.25.0.10, 10.25.0.11, 10.25.30.10.
With this enhancement, `bind 10.25.0.0/24` would bind to 10.25.0.10 and 10.25.0.11, but not 10.25.30.10.
It would act the same as `bind 10.25.0.10 10.25.0.11 `

Does that accurately describe your intent?

2022-05-05 14:45 UTC, chrisohaver commented
> By binding to a subnet, you intend it to be shorthand for binding to every address that falls within that subnet.
>
> For example: Let's say you have a system with three addresses 10.25.0.10, 10.25.0.11, 10.25.30.10.
With this enhancement, bind 10.25.0.0/24 would bind to 10.25.0.10 and 10.25.0.11, but not 10.25.30.10.
It would act the same as bind 10.25.0.10 10.25.0.11


IIUC however, the code in the PR behaves differently.  It looks like tries to bind to every possible IP address in the subnet, regardless of whether or not the addresses actually exists on the local system. If one of the addresses does not exist n the local system, I think CoreDNS will fail to start.

2022-05-05 20:12 UTC, chrisohaver requested changes
It looks like the code tries to bind to every possible IP address in the subnet, regardless of whether or not the addresses actually exists on the local system. If any of the addresses do not exist on the local system, CoreDNS will fail to start.

The README needs to be updated to reflect the new feature.

2022-05-06 08:17 UTC, victory460 commented
> OK, that didn't clarify it for me at all. But I'm guessing that...
> 
> By binding to a subnet, you intend it to be shorthand for binding to every address that falls within that subnet.
> 
> For example: Let's say you have a system with three addresses 10.25.0.10, 10.25.0.11, 10.25.30.10. With this enhancement, `bind 10.25.0.0/24` would bind to 10.25.0.10 and 10.25.0.11, but not 10.25.30.10. It would act the same as `bind 10.25.0.10 10.25.0.11 `
> 
> Does that accurately describe your intent?

![](https://cdn.jsdelivr.net/gh/gomakesix/mdimg/20220506160317.png)
For example scenes in the picture, configure different nameservers at machines in different vpcs, then we can analyze which vpc  the request comes from, according to the different server's ip obtained by coredns.

2022-05-06 08:33 UTC, victory460 commented
> It looks like the code tries to bind to every possible IP address in the subnet, regardless of whether or not the addresses actually exists on the local system. If any of the addresses do not exist on the local system, CoreDNS will fail to start.
> 
> The README needs to be updated to reflect the new feature.

Thanks for your reply. I update the README about the new feature now.

2022-05-06 20:49 UTC, chrisohaver requested changes
I'm not sold on whether or not this feature should be included.
* It doesn't add new functionality.  the same could be done by listing each IP.
* It adds complexity.
* The use case it facilitates feels obscure and on the edge.

If we do decide this should be included, it should also ...
* support ipv6
* only bind to addresses that exist on the system AND fall within the subnet. IMO, this would make the feature slightly more useful (and may also simplify the code to iterate over local address instead of enumerating each ip in the subnet).

2022-05-13 13:41 UTC, Freeaqingme commented
I haven't thoroughly reviewed the code, but is this feature compatible with IPv6?

Especially this line makes me think that it was designed specifically for IPv4 only: 
> if strings.Contains(a, ".") && strings.Contains(a, "/") {

2022-05-13 13:44 UTC, victory460 commented
> I haven't thoroughly reviewed the code, but is this feature compatible with IPv6?
> 
> Especially this line makes me think that it was designed specifically for IPv4 only:
> 
> > if strings.Contains(a, ".") && strings.Contains(a, "/") {

Yes. It was designed specifically for IPv4 only.

2022-06-21 02:12 UTC, closed without merging