recover from panic log including stacktrace to help finding the origin
coredns/coredns pull request #5392
Opened 2022-05-20 11:55 UTC by rhatlapa

Currently CoreDNS doesn't log stactrace when recovering from panic which makes it hard to find the source from where the panic originates. This change proposes including the stacktrace as part of the logged message.

### 1. Why is this pull request needed and what does it do?
Currently when CoreDNS recovers from a panic, it just logs the error message without the stacktrace.

See difference output log from artificially added panic to whoami plugin

```
[ERROR] Recovered from panic in server: "dns://:53" index out of range [0] with length 0
```

After the proposed update you will get it including stacktrace which will help to find the origin:
```
[ERROR] Recovered from panic in server: "dns://:53" index out of range [0] with length 0
goroutine 55 [running]:
runtime/debug.Stack()
	/Users/radim.hatlapatka/sdk/go1.17.8/src/runtime/debug/stack.go:24 +0x88
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS.func1(0x14000682180, 0x140004c1e20, 0x1400060a000)
	/Users/radim.hatlapatka/projects/upstream/coredns/core/dnsserver/server.go:217 +0x48
panic({0x1047fd300, 0x104ba7638})
	/Users/radim.hatlapatka/sdk/go1.17.8/src/runtime/panic.go:1038 +0x21c
github.com/coredns/coredns/plugin/whoami.Whoami.ServeDNS({}, {0x104bf4498, 0x140002873e0}, {0x104c24de8, 0x1400012c340}, 0x1400060a000)
	/Users/radim.hatlapatka/projects/upstream/coredns/plugin/whoami/whoami.go:28 +0x94
github.com/coredns/coredns/plugin.NextOrFailure({0x1042c8b15, 0x3}, {0x104bdd048, 0x105c71b08}, {0x104bf4498, 0x140002873e0}, {0x104c24de8, 0x1400012c340}, 0x1400060a000)
	/Users/radim.hatlapatka/projects/upstream/coredns/plugin/plugin.go:80 +0x1ec
github.com/coredns/coredns/plugin/log.Logger.ServeDNS({{0x104bdd048, 0x105c71b08}, {0x1400011fd70, 0x1, 0x1}, {}}, {0x104bf4498, 0x140002873e0}, {0x104c24ef0, 0x14000316198}, ...)
	/Users/radim.hatlapatka/projects/upstream/coredns/plugin/log/log.go:36 +0x2ac
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0x14000682180, {0x104bf4498, 0x140002873e0}, {0x104c24ef0, 0x14000316198}, 0x1400060a000)
	/Users/radim.hatlapatka/projects/upstream/coredns/core/dnsserver/server.go:281 +0x620
github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1({0x104c269c0, 0x140002c2300}, 0x1400060a000)
	/Users/radim.hatlapatka/projects/upstream/coredns/core/dnsserver/server.go:129 +0xe4
github.com/miekg/dns.HandlerFunc.ServeDNS(0x1400020a040, {0x104c269c0, 0x140002c2300}, 0x1400060a000)
	/Users/radim.hatlapatka/go/pkg/mod/github.com/miekg/dns@v1.1.49/server.go:37 +0x40
github.com/miekg/dns.(*Server).serveDNS(0x14000606000, {0x14000578800, 0x2c, 0x200}, 0x140002c2300)
	/Users/radim.hatlapatka/go/pkg/mod/github.com/miekg/dns@v1.1.49/server.go:659 +0x3cc
github.com/miekg/dns.(*Server).serveUDPPacket(0x14000606000, 0x140002a80b0, {0x14000578800, 0x2c, 0x200}, {0x104c185b0, 0x1400000f4c0}, 0x14000344020, {0x0, 0x0})
	/Users/radim.hatlapatka/go/pkg/mod/github.com/miekg/dns@v1.1.49/server.go:603 +0x1bc
created by github.com/miekg/dns.(*Server).serveUDP
	/Users/radim.hatlapatka/go/pkg/mod/github.com/miekg/dns@v1.1.49/server.go:533 +0x3a8
```

### 2. Which issues (if any) are related?
none
### 3. Which documentation changes (if any) need to be made?
none
### 4. Does this introduce a backward incompatible change or deprecation?
no

2022-05-20 12:57 UTC, johnbelamaric commented
Have you tried the `errors` or `debug` plugins?

2022-05-20 13:07 UTC, chrisohaver commented
> Have you tried the `errors` or `debug` plugins?

IIUC, _debug_ prints a stack trace, but does do by disabling panic recovery, which would be problematic if trying to track down an issue that can only be reproduced in a production env.

I think it would be nice if this was an option.  e.g. a way to enable stack trace logging with _debug_ without disabling recovery.

2022-05-20 13:38 UTC, Tantalor93 commented
> > Have you tried the `errors` or `debug` plugins?
> 
> IIUC, _debug_ prints a stack trace, but does do by disabling panic recovery, which would be problematic if trying to track down an issue that can only be reproduced in a production env.
> 
> I think it would be nice if this was an option. e.g. a way to enable stack trace logging with _debug_ without disabling recovery.

`debug` plugin also enables debug logging, which can be quite verbose on production environments, so having this as option for debug plugin would have sideeffect of enabling debug logging on production environment.

I think it makes sense to have stacktrace of panics logged always as it is not expected error in any request processing flow, it is programatic error and should be handled by plugins more gracefully. What is the benefit of not logging the stacktrace? It makes debugging issues quite cumbersome.

2022-05-20 13:47 UTC, chrisohaver commented
> What is the benefit of not logging the stacktrace?

Perhaps the thought was that stack traces themselves are too verbose for a production environment?

> debug plugin also enables debug logging, which can be quite verbose on production environments

How about an option in _error_ to print stack traces on recoveries.

2022-05-23 06:13 UTC, rhatlapa commented
I find the panic log without stacktrace almost use-less as with the rather large CoreDNS codebase you have hard time figuring out from where the error originates. Still I will extend the error plugin to include configurability of this.

2022-05-23 08:51 UTC, rhatlapa commented
I've updated the error plugin and you can enable the stacktrace printing by including `panicRecoveryStacktrace` in the `errors` plugin.
```
.:53 {
    errors {
      panicRecoveryStacktrace
    }
}
```

2022-05-23 12:54 UTC, chrisohaver commented on plugin/errors/README.md
> +	panicRecoveryStacktrace
```suggestion
	stacktrace
```

2022-05-23 12:55 UTC, chrisohaver commented on plugin/errors/README.md
> +Option `panicRecoveryStacktrace` enables logging of stacktrace in case of panic recovery.
```suggestion
Option `stacktrace` will log a stacktrace during panic recovery.
```

2022-05-23 13:00 UTC, chrisohaver requested changes
Thanks, looks good.  Suggesting a shorter name for the new option.

2022-05-23 13:00 UTC, chrisohaver commented on plugin/errors/README.md
> +Option `panicRecoveryStacktrace` enables logging of stacktrace in case of panic recovery.
```suggestion
Option `stacktrace` will log a stacktrace during panic recovery.
```

2022-05-23 13:00 UTC, chrisohaver commented on plugin/errors/README.md
> +	panicRecoveryStacktrace
```suggestion
	stacktrace
```

2022-05-23 13:00 UTC, chrisohaver commented on plugin/errors/setup.go
> +			case "panicRecoveryStacktrace":
```suggestion
			case "stacktrace":
```

2022-05-23 13:00 UTC, chrisohaver commented on plugin/errors/setup_test.go
> +            panicRecoveryStacktrace
```suggestion
            stacktrace
```

2022-05-23 13:00 UTC, chrisohaver commented on plugin/errors/setup_test.go
> +            panicRecoveryStacktrace
```suggestion
            stacktrace
```

2022-05-23 15:51 UTC, rhatlapa commented
Thank you for review, suggestions incorporated.

2022-05-23 16:35 UTC, chrisohaver approved these changes
LGTM

2022-05-24 09:03 UTC, rhatlapa commented
@johnbelamaric , @yongtang , @stp-ip , @miekg , could you please take a look whether it looks OK also from your point of views?

2022-05-24 10:17 UTC, yongtang commented
@rhatlapa your commit's email may not be registered with your GitHub handle. Can you see if this can be fixed?  If this is not fixed then after the merge the author info might be lost and the contribution may not be correctly associated to your GitHub handle.

2022-05-24 10:26 UTC, rhatlapa commented
Thanks fro pointing it out, should be fixed now.

2022-05-24 12:36 UTC, merged