plugin/rewrite: Support min and max TTL values
coredns/coredns pull request #5508
Opened 2022-07-12 11:35 UTC by AndreasHuber-CH

Signed-off-by: Andreas Huber <andreas.huber@nagra.com>

### 1. Why is this pull request needed and what does it do?
Add support for specifying min & max TTL values in rewrite plugin.

### 2. Which issues (if any) are related?
Implements enhancement described in #5501

### 3. Which documentation changes (if any) need to be made?
I've updated README.md to give some examples of the new TTL config.

### 4. Does this introduce a backward incompatible change or deprecation?
The change is backward compatible

2022-07-12 13:31 UTC, chrisohaver requested changes

2022-07-12 13:31 UTC, chrisohaver commented on plugin/rewrite/README.md
> +It is possible to supply a range of TTL values in the `SECONDS` parameters instead of a single value.
The Syntax section also needs to be updated to reflect the new syntax.

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +func newTTLRuleBase(nextAction string, minTtl uint32, maxTtl uint32) ttlRuleBase {
```suggestion
func newTTLRuleBase(nextAction string, minTtl, maxTtl uint32) ttlRuleBase {
```

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +		if err != nil || i > 2147483647 || i < 0 {
what is number `2147483647`? Seems like a random magic number, maybe worth introducing named constant for this with proper explanation?

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +			return uint32(0), uint32(0), false
no need for explicit type?
```suggestion
			return 0, 0, false
```

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +				return uint32(0), uint32(0), false
```suggestion
				return 0, 0, false
```

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +			return uint32(0), uint32(0), false
```suggestion
			return 0, 0, false
```

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +				return uint32(0), uint32(0), false
```suggestion
				return 0, 0, false
```

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +				return uint32(0), uint32(0), false
```suggestion
				return 0, 0, false
```

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +			return uint32(0), uint32(0), false
```suggestion
			return 0, 0, false
```

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +		return uint32(min), uint32(max), true
I think you need to use `strconv.ParseUint(value, 10, 32)`

2022-07-14 17:36 UTC, Tantalor93 commented on plugin/rewrite/ttl.go
> +		i, err := strconv.Atoi(s[0])
`strconv.ParseUint(s[1], 10, 32)` would be better I think? That will also check that value will fit uint32 range. Also in other conversions

2022-08-02 13:06 UTC, AndreasHuber-CH commented
Hi,
I was on vacation the last weeks so it took a bit more time to respond.
I've pushed a simplification using strconv.ParseUint and removing the range checks.
The code I've written before was based on the existing code, but it certainly looks nicer now.

2022-08-02 13:16 UTC, chrisohaver requested changes
Thanks.  Minor doc changes suggested.

2022-08-02 13:16 UTC, chrisohaver commented on plugin/rewrite/README.md
> +rewrite [continue|stop] ttl [exact|prefix|suffix|substring|regex] STRING [SECONDS|minSECONDS-maxSECONDS]
```suggestion
rewrite [continue|stop] ttl [exact|prefix|suffix|substring|regex] STRING [SECONDS|MIN-MAX]
```

2022-08-02 13:16 UTC, chrisohaver commented on plugin/rewrite/README.md
> +If a range is supplied, the TTL value is increased to the configured minimum value if it is below,
```suggestion
If a range is supplied, the TTL value is set to `MIN` if it is below,
```

2022-08-02 13:16 UTC, chrisohaver commented on plugin/rewrite/README.md
> +or decreased to the configured maximum value if it is above.
```suggestion
or set to MAX if it is above.
```

2022-08-03 10:57 UTC, Tantalor93 reviewed
Please fix the DCO, otherwise LGTM

2022-08-17 19:19 UTC, Tantalor93 approved these changes

2022-08-17 19:33 UTC, merged