Add PTR records to supported types
coredns/coredns pull request #5565
Opened 2022-08-10 09:26 UTC by xbulat

### 1. Why is this pull request needed and what does it do?
CoreDNS should support PTR record because it contains domain values that also might be overwritten 

### 2. Which issues (if any) are related?

https://github.com/coredns/coredns/issues/2837

### 3. Which documentation changes (if any) need to be made?
Was added `Explicit Response Value Rewrite` with an example of how to use overwrite of values in the `ANSWER SECTION`

### 4. Does this introduce a backward incompatible change or deprecation?
No

2022-08-10 15:01 UTC, greenpau requested changes
Overall lgtm. Just a minor doc change.

2022-08-10 15:01 UTC, greenpau commented on plugin/rewrite/README.md
> +```
Please add extra line here.

2022-08-12 12:19 UTC, chrisohaver commented on plugin/rewrite/README.md
> +#### Explicit Response Value Rewrite
Thanks for the PR.

```suggestion
##### Example: PTR Response Value Rewrite
```

FWIW, I also happen to find the existing use of "Explicit ..." in other subtitles to indicate these are examples of the previous section to be confusing.

2022-08-12 18:00 UTC, greenpau approved these changes

2022-08-14 14:26 UTC, merged