plugin/edns: remove truncating of question section on bad EDNS version
coredns/coredns pull request #5787
Opened 2022-11-30 20:32 UTC by kaplanben

### 1. Why is this pull request needed and what does it do?
EDNS requests of "Unknown Version" removed the query section altogether. 
Not sure why since this is not required (see [link](https://kb.isc.org/docs/edns-compatibility-dig-queries))

This causes issues with DNS solutions that use this information (initial queried name, type, and class) in order to route the response to the right client (e.g. PDNS).

The change here is to keep the initial query section as is.

### 2. Which issues (if any) are related?
[5785](https://github.com/coredns/coredns/issues/5785)

### 3. Which documentation changes (if any) need to be made?

### 4. Does this introduce a backward incompatible change or deprecation?
None that I'm aware of since the ENDS "Unknown Version" requirements are clear and do not include removing the query section.

2022-11-30 21:49 UTC, chrisohaver commented
> EDNS requests of "Unknown Version" removed the query section altogether. Not sure why ...

Yeah.  The colorful comments don't explain _why_. I mean, it's fair to assume there was an actual reason, but we don't know what that reason was. Presumably "something" didn't work when there was a question (during local manual testing?). But the comments are at least helpful by implying the need to remove the question was deemed dubious at the time. The code is 7 years old now, and the original author (and CoreDNS founder) is no longer an active maintainer.

2022-11-30 21:52 UTC, chrisohaver approved these changes

2022-11-30 21:54 UTC, Tantalor93 commented
I think it would be worth to cover this functionality better by unit tests https://github.com/coredns/coredns/blob/master/plugin/pkg/edns/edns_test.go#L9 WDYT @chrisohaver? Like check the returned dns.Msg

2022-11-30 21:55 UTC, Tantalor93 commented
but otherwise, I agree, with this change

2022-11-30 22:05 UTC, chrisohaver commented
> I think it would be worth to cover this functionality better by unit tests

Yeah - the existing tests cover very poorly - ignoring the returned message and only checking the error returned.

2022-11-30 22:06 UTC, chrisohaver requested changes
@kaplanben can you please fix the existing unit tests to actually validate the messages returned by `Versions`.  Thanks!

2022-12-01 12:51 UTC, Tantalor93 commented on plugin/pkg/edns/edns_test.go
>  func TestVersionNoEdns(t *testing.T) {
can you add an assertion here that the response message is nil? So it is actually asserted that it is expected in case of no EDNS?

2022-12-01 13:50 UTC, Tantalor93 approved these changes

2022-12-01 14:06 UTC, chrisohaver approved these changes
Lgtm thanks!

2022-12-01 14:07 UTC, merged