chore: add ut
coredns/coredns pull request #6107
Opened 2023-05-22 14:43 UTC by yyzxw

### 1. Why is this pull request needed and what does it do?

Improve unit test coverage.

### 2. Which issues (if any) are related?

### 3. Which documentation changes (if any) need to be made?

### 4. Does this introduce a backward incompatible change or deprecation?

2023-05-25 13:14 UTC, chrisohaver commented on .gitignore
> +./.idea
please refer this

2023-05-26 12:22 UTC, Tantalor93 requested changes

2023-05-26 12:22 UTC, Tantalor93 commented on plugin/bind/setup_test.go
> +func Test_isIn(t *testing.T) {
this is admirable, but can we rather remove the function `isIn` and rather replace it with `slices.Contains(except, ip)` ?

2023-05-26 12:22 UTC, Tantalor93 commented on request/request_test.go
> +type fakeResponseWriter struct {
can we rather add this functionality into `test.responsewriter`?

2023-05-28 02:49 UTC, closed without merging