Change default value to 1232
coredns/coredns pull request #6183
Opened 2023-06-30 16:06 UTC by pemensik

As specified by DNS flag day 2020, good and decent default value avoiding fragmentation issues should be 1232. It is quite likely 1500 would work reliably on local ethernet networks.

Value 512 is set implicitly and must be used for all clients, which did not include OPT RR with explicit value they support.

Since MR #5368 it should work correctly.

### 1. Why is this pull request needed and what does it do?
Changes EDNS0 default value to recommended value.

### 2. Which issues (if any) are related?
- #5366

### 3. Which documentation changes (if any) need to be made?
- https://github.com/coredns/coredns.io/issues/295

### 4. Does this introduce a backward incompatible change or deprecation?
It removes the confusion around EDNS0 size. It may create behaviour change.

2023-06-30 16:48 UTC, pemensik commented
I think this plugin is somehow too simple. It can only further reduce EDNS accepted size after https://github.com/coredns/coredns/issues/5366. It is not able to add EDNS header to forwarded query, which I think documentation for it suggests.

If can only reduce accepted response size for queries, which already has EDNS0 header.

2023-06-30 17:16 UTC, pemensik commented
I think the example, which uses bufsize with forward plugin, creates confusion. It were originally able to add EDNS0 header to forwarded query. After MR https://github.com/coredns/coredns/pull/5368 it cannot do that anymore. There are cases where adding EDNS0 header is desired. But in case the response is larger than originating client query allowed, it would have to return response with TC bit set *and* EDNS0 header removed. That seems not possible anymore.

2023-06-30 18:12 UTC, pemensik commented
Related change in OpenShift: https://github.com/openshift/cluster-dns-operator/pull/370

2023-06-30 20:30 UTC, pemensik commented
It seems to me similar algorithm should be made as in https://github.com/coredns/coredns/pull/4085. When incoming query arrives, it should be safe to set internal supported EDNS0 size on the forwarded query. When the answer arrives, OPT RR may need to be removed from response, if it were not in original request.

2023-07-04 14:21 UTC, Tantalor93 approved these changes
Thanks for the PR, LGTM! would be nice to include it into `1.11.0` release
FYI @chrisohaver

2023-07-04 14:38 UTC, Tantalor93 requested changes
oh, looks like `TestSetupBufsize` needs to be [updated](https://github.com/coredns/coredns/actions/runs/5425254281/jobs/9927741740?pr=6183). Shame on me for approving before triggering pipelines 🙂

2023-07-04 14:45 UTC, chrisohaver commented
I’d like to review all recent PRs relating to Edns before they merge.

2023-07-04 15:16 UTC, Tantalor93 commented
FYI @pemensik all commits must be signed https://github.com/coredns/coredns/pull/6183/checks?check_run_id=14770904337 🙂

2023-07-04 15:59 UTC, pemensik commented
Okay, I think it is ready for review now.

2023-07-04 16:27 UTC, Tantalor93 approved these changes

2023-07-05 13:14 UTC, chrisohaver requested changes
Thanks! The flag-day advised default value LGTM.  Minor changes to wording in docs requested.

2023-07-05 13:14 UTC, chrisohaver commented on plugin/bufsize/README.md
> +*bufsize* reduces a requester's UDP payload size.
```suggestion
*bufsize* limits a requester's UDP payload size to within a maximum value. If a request with an OPT RR has a bufsize greater than the limit, the bufsize of the request will be reduced. Otherwise the request is unaffected.
```

IMO "limit" is the correct word here.  It implies more directly that the value is limited by the configured value, and would not be "reduced", if below the limit.

2023-07-05 13:14 UTC, chrisohaver commented on plugin/bufsize/README.md
> +*bufsize* - reduces EDNS0 buffer size to prevent IP fragmentation.
```suggestion
*bufsize* - limits EDNS0 buffer size to prevent IP fragmentation.
```

2023-07-06 17:54 UTC, pemensik commented on plugin/bufsize/README.md
> +*bufsize* reduces a requester's UDP payload size.
Okay, explaining it more makes sense. Added just few line breaks to your version.

2023-07-06 18:11 UTC, chrisohaver approved these changes
lgtm thanks!

2023-07-07 11:22 UTC, Tantalor93 requested changes
`TestSetupBufsize` needs adjustment https://github.com/coredns/coredns/actions/runs/5478594030/jobs/9979672394?pr=6183

```
Test 0: Bufsize not correctly set for input bufsize. Expected: 512, actual: 1232
```

2023-07-07 17:18 UTC, pemensik commented
> `TestSetupBufsize` needs adjustment https://github.com/coredns/coredns/actions/runs/5478594030/jobs/9979672394?pr=6183
> 
> ```
> Test 0: Bufsize not correctly set for input bufsize. Expected: 512, actual: 1232
> ```

Ouch, I have force-pushed previous version with just corrected documentation. I have already fixed this.

2023-07-07 19:38 UTC, Tantalor93 approved these changes
LGTM

2023-07-10 14:49 UTC, merged