plugin/forward add ignore_server_failure for masking upstream server …
coredns/coredns pull request #6204
Opened 2023-07-14 13:05 UTC by pschou

### 1. Why is this pull request needed, and what does it do?

Adds the ability to mask server failure replies from a proxied DNS server.  This change makes CoreDNS "just work" in broken/firewalled environments.

For example, an IPv6 incompatible DNS appliance-- enables a stand-in proxy fix where IPv6 is not fully supported yet.  This option allows you to "ignore errors" and reply with an empty record.  When docker or Kubernetes sits behind a firewall appliance that blocks AAAA records from being resolved, the docker API sits and waits seconds to do multiple tries in hopes of getting a SUCCESS reply.  This flag masks this issue go away, and thus, the infrastructure runs faster.

In gist, it takes any SERVER-FAIL replies and switches them to SUCCESS to give the application a "no records found" reply.

### 2. Which issues (if any) are related?

None (that I know of)

### 3. Which documentation changes (if any) need to be made?

The plugin README has been updated.

### 4. Does this introduce a backward incompatible change or deprecation?

No

2023-07-14 13:16 UTC, chrisohaver commented
Thanks for contributing! 

> When docker or Kubernetes sits behind a firewall appliance that blocks AAAA records from being resolved, the docker API sits and waits seconds to do multiple tries

There may be other ways to solve the issue, with existing plugins such as _acl_ or _template_.
e.g. you can make coredns respond to all AAAA requests with empty response (aka nodata) with _acl_ plugin using `filter type AAAA`.

2023-07-14 13:43 UTC, pschou commented
> Thanks for contributing!
> 
> > When docker or Kubernetes sits behind a firewall appliance that blocks AAAA records from being resolved, the docker API sits and waits seconds to do multiple tries
> 
> There may be other ways to solve the issue, with existing plugins such as _acl_ or _template_. e.g. you can make coredns respond to all AAAA requests with empty response (aka nodata) with _acl_ plugin using `filter type AAAA`.

I agree that this is a potential avenue of resolution if we want all AAAA records to be taken away, but I still want IPv6 to be functional and enabled as much as possible-- so turning off all IPv6 goes against the plan to make IPv6 work where ever possible.

The SERVER-FAIL is something that the DNS appliance keeps throwing back.  It seems the DNS administrators think that SERVER-FAIL reply is the right course of action, but this keeps tripping up my Kubernetes deployments because they just stall whenever I try to deploy on a system.

2023-07-17 11:36 UTC, palmerrb2000 commented
This fixed a longstanding problem for me. A sincere thank you to all who contribute!

2023-07-17 12:00 UTC, chrisohaver commented
Conceptually, this class of feature is a better fit for the _rewrite_ plugin.  It's a plugin that rewrites/overrides aspects of request and response.  E.g. It could be implemented by adding a new `FIELD` type option to the _rewrite_ plugin: `code FROM TO`.

Also if implemented in the _rewrite_ plugin, the response code override could be applied to a response from any plugin, not just _forward_ plugin.  So it would be more utilitarian, applicable to more situations.

2023-07-18 17:12 UTC, pschou commented
> Conceptually, this class of feature is a better fit for the _rewrite_ plugin. It's a plugin that rewrites/overrides aspects of request and response. E.g. It could be implemented by adding a new `FIELD` type option to the _rewrite_ plugin: `code FROM TO`.
> 
> Also if implemented in the _rewrite_ plugin, the response code override could be applied to a response from any plugin, not just _forward_ plugin. So it would be more utilitarian, applicable to more situations.

This is a very good point and I concur that a rewrite type would be a better fit for more diverse use cases.  I have amended the PR to realize this suggestion.

2023-07-20 12:03 UTC, pschou commented
@chrisohaver Do you think the documentation should use OLD/NEW or FROM/TO?  I am considering switching it, but I would like to see what you think.

2023-07-20 12:30 UTC, chrisohaver commented
> @chrisohaver Do you think the documentation should use OLD/NEW or FROM/TO? I am considering switching it, but I would like to see what you think.

Best to be consistent with existing wording.   I think it uses from/to.

2023-07-20 12:30 UTC, chrisohaver reviewed
Thanks!

2023-07-20 12:30 UTC, chrisohaver commented on plugin/rewrite/README.md
> +The values of OLD and NEW can be any of the following:
Should mention that you accept both numeric and string representation for OLD and NEW response code.

2023-07-20 12:30 UTC, chrisohaver commented on plugin/rewrite/README.md
> +being set to `15`:
Please update sentence for rcode example

2023-07-20 12:30 UTC, chrisohaver commented on plugin/rewrite/rcode.go
> +	}
You can use the `dns.RcodeToString` map here.

2023-07-20 13:08 UTC, wondywang commented
#6214

2023-07-20 19:29 UTC, pschou commented on plugin/rewrite/rcode.go
> +	}
Good catch, I didn't see that map!

2023-07-21 06:27 UTC, wondywang commented
This PR also addresses a particular scenario I encountered. A big thank you to all contributors!

2023-07-21 13:19 UTC, chrisohaver commented
Fix import ordering and LGTM. Deferring final approval/merge to the rewrite plugin codeowners.

2023-08-26 11:10 UTC, greenpau commented
@pschou , please address the go coverage errors. Otherwise, LGTM.

2023-08-26 11:12 UTC, greenpau requested changes
LGTM. Please address presubmit check.

2023-08-26 11:51 UTC, greenpau commented
@pschou , there are some other test failing too:

- DCO Action required after 1s — DCO

- ci/circleci: kubernetes-tests — Your tests failed on CircleCI

2023-08-26 12:27 UTC, pschou commented
@greenpau, this build process is fragile.

The pull approval was delayed all because of a single new line character, "\n", the test to verify that the imports are in the right format fail-- ok, I understand that consistency is important.  So, I add a single new line character to space the imports apart, and now other checks that previously passed are failing due to a curl because of an external API change at go.dev.  This issue is not related to this pull request, out of scope.

When pulling down this endpoint, one will find two lines are returned:
```
$ curl 'https://go.dev/VERSION?m=text'
go1.21.0
time 2023-08-04T20:14:06Z
```


---
LATEST=$(curl -s https://go.dev/VERSION?m=text)
curl https://dl.google.com/go/${LATEST}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1
curl: (6) Could not resolve host: time
curl: (3) URL using bad/illegal format or missing URL
---

Maybe a proposed fix would look like this:
---
LATEST=($(curl -s https://go.dev/VERSION?m=text))
curl https://dl.google.com/go/${LATEST[0]}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1
---

Note that every check passed before this external API response change:
  https://app.circleci.com/pipelines/github/coredns/coredns/6794/workflows/4c459d4c-0fb8-4049-a554-743276e69d85/jobs/6867

Now it is failing due to the external API change:
  https://app.circleci.com/pipelines/github/coredns/coredns/6951/workflows/336e30ed-1b21-4de5-bcc5-8b83de43df91/jobs/7025

2023-08-26 13:27 UTC, chrisohaver commented
Please rebase

2023-08-26 15:59 UTC, pschou commented
Ok, done 👍

2023-08-27 02:19 UTC, greenpau approved these changes
LGTM

2023-08-27 02:20 UTC, merged