Set IP_TRANSPARENT on the sockets
coredns/coredns pull request #7018
Opened 2024-12-04 09:39 UTC by kosmas-valianos

### 1. Why is this pull request needed and what does it do?
It enables coreDNS to work as a transparent DNS proxy. You can capture DNS requests going to IP A and redirect them to coreDNS IP B. A classic example setup is to use `TPROXY` in the `mangle` table in the `PREROUTING` chain to redirect the packets to coreDNS

### 2. Which issues (if any) are related?
Not related to any Open issue. Needed in our setup to have coreDNS as transparent DNS Proxy and at the moment we have to patch coreDNS.

### 3. Which documentation changes (if any) need to be made?
In places that it is mentioned that coreDNS supports/sets `SO_REUSEPORT` it can be mentioned that it also supports/sets `IP_TRANSPARENT`

### 4. Does this introduce a backward incompatible change or deprecation?
`IP_TRANSPARENT` is supported since Linux 2.6.24

2025-03-26 12:29 UTC, kosmas-valianos commented
Any feedback here?

2025-08-22 20:48 UTC, dilyevsky requested changes
This change will require CAP_NET_ADMIN which I don't believe we currently require. I don't think this should be turned on by default.

2025-08-24 07:48 UTC, kosmas-valianos commented
> This change will require CAP_NET_ADMIN which I don't believe we currently require. I don't think this should be turned on by default.

How should it be controlled then? Ideally it would be with a "core" plugin, but plugins are high level and they don't hook in such low level things

2025-08-28 20:55 UTC, dilyevsky commented
I think top-level `ip_transparent` config option should suffice. The other thing I noticed is `reuseport.Listen` is called from a bunch of places (pprof and others) so another reason why it can't be default.

2025-08-29 11:34 UTC, kosmas-valianos commented
> I think top-level `ip_transparent` config option should suffice. The other thing I noticed is `reuseport.Listen` is called from a bunch of places (pprof and others) so another reason why it can't be default.

Hmm do you mean something like the `bind` where it  basically edits the `type Config struct {` ? To set a boolean in that Config struct which can been toggled by `ip_transparent`. That would work to set the Config but then somehow needs to make it all the way to the `reuseport` package and that package is Config agnostic. Hmm and those Listen() in there are basically called from
```
// ListenPacket implements caddy.UDPServer interface.
func (s *Server) ListenPacket() (net.PacketConn, error) {
	p, err := reuseport.ListenPacket("udp", s.Addr[len(transport.DNS+"://"):])
```
which means you cannot simply pass Config in there. I don't see any non invasive way to do it :( If there is an example in the codebase that such a low level thing is configurable point me at

2026-01-10 16:09 UTC, closed without merging